services:
  - type: web
    name: vnr-keys-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://vnr-keys.vercel.app
    healthCheckPath: /api/health
